{{- if .Values.monitoring.exportarr.create }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "service.name" . }}-exporter
    app.kubernetes.io/instance: {{ include "service.name" . }}-exporter
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ include "service.name" . }}-exporter
    app.kubernetes.io/instance: {{ include "service.name" . }}-exporter
  ports:
    - name: monitoring
      port: 9707
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "service.name" . }}-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "service.name" . }}-exporter
    app.kubernetes.io/instance: {{ include "service.name" . }}-exporter
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "service.name" . }}
  endpoints:
    - port: monitoring
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      path: /metrics
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: {{ include "service.name" . }}-exporter
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "service.name" . }}-exporter
    app.kubernetes.io/instance: {{ include "service.name" . }}-exporter
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "service.name" . }}-exporter
      app.kubernetes.io/instance: {{ include "service.name" . }}-exporter
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "service.name" . }}-exporter
        app.kubernetes.io/instance: {{ include "service.name" . }}-exporter
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "monitoring"
    spec:
      containers:
        - name: {{ include "service.name" . }}-exporter
          image: ghcr.io/onedr0p/exportarr:{{ .Values.monitoring.exportarr.version | default "latest" }}
          imagePullPolicy: IfNotPresent
          args:
            - {{ include "service.name" . }}
          env:
            - name: PORT
              value: "9707"
            - name: URL
              value: "http://{{ include "service.name" . }}.{{ .Release.Namespace }}.svc.cluster.local:{{ (index .Values.container.ports 0).containerPort }}"
            - name: APIKEY
              value: {{ .Values.monitoring.exportarr.apiKey | quote }}
              # valueFrom:
              #   secretKeyRef:
              #     name: {{ include "service.name" . }}-api-key
              #     key: api-key
          ports:
            - name: monitoring
              containerPort: 9707
          livenessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: monitoring
            failureThreshold: 5
            periodSeconds: 10
          resources:
            requests:
              cpu: 100m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
{{- end }}
