{{- if .Values.ingressRoutes }}
{{- $root := . }}
{{- $wildcardMode := eq .Values.certificate.tls.mode "wildcard" }}

{{- range $routeItem := .Values.ingressRoutes }}
{{- $certHost := "" }}
{{- if $routeItem.certificateHostname }}
  {{- $certHost = tpl $routeItem.certificateHostname $root }}
{{- end }}
{{- $backendService := $routeItem.backendService | default dict }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ tpl $routeItem.name $root }}
  namespace: {{ $root.Release.Namespace }}
  annotations:
    {{- if ($routeItem.externalDns | default dict).enabled }}
    external-dns.alpha.kubernetes.io/target: {{ include "cluster.fqdn" $root }}
    {{- end }}
    kubernetes.io/ingress.class: traefik
    {{- if and $routeItem.homepage $root.Values.homepage.enabled }}
      {{- include "ingress.homepageAnnotations" $root | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/component: backend
    {{- include "service.labels" $root | nindent 4 }}
    {{- with $routeItem.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: {{ tpl $routeItem.match $root }}
      {{- with $routeItem.middlewares }}
      middlewares:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      services:
      - kind: Service
        name: {{ $backendService.name | default (include "service.name" $root) }}
        namespace: {{ $backendService.namespace | default $root.Release.Namespace }}
        passHostHeader: true
        port: {{ $backendService.port | default (include "service.httpPort" $root) }}
        {{- with $backendService.scheme }}
        scheme: {{ . }}
        {{- end }}
        {{- with $backendService.serversTransport }}
        serversTransport: {{ . }}
        {{- end }}
  {{- if (or (not $wildcardMode) $certHost) }}
  tls:
    secretName: {{ include "service.name" $root }}-cert
  {{- else }}
  tls: {}
  {{- end }}
---
{{- end }}
{{- end }}

{{- range .Values.customMiddleware.definitions }}
---
{{ include "service.render" (dict "value" . "context" $) }}
{{- end }}
