{{- if .Values.ingress.create }}
{{- $wildcardMode := eq .Values.ingress.tls.mode "wildcard" }}
{{- $extraCertHosts := list }}
{{- range .Values.ingress.extraRoutes }}
  {{- if .certificateHostname }}
    {{- $extraCertHosts = append $extraCertHosts (tpl .certificateHostname $) }}
  {{- end }}
{{- end }}
{{- $needsCertificate := or (not $wildcardMode) (gt (len $extraCertHosts) 0) }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Values.ingress.defaultRoute.externalDns.enabled }}
    external-dns.alpha.kubernetes.io/target: {{ include "cluster.fqdn" . }}
    {{- end }}
    kubernetes.io/ingress.class: traefik
    {{- if .Values.homepage.enabled }}
      {{- include "ingress.homepageAnnotations" . | nindent 4 }}
    {{- end }}
  labels:
    app.kubernetes.io/component: backend
    {{- include "service.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
    - kind: Rule
      match: {{ printf "Host(`%s.%s`)" (include "service.name" .) (include "cluster.fqdn" .) }}
      middlewares:
        - name: https-redirectscheme
          namespace: traefik
        {{- if .Values.ingress.defaultRoute.extraMiddlewares }}
        {{- tpl (.Values.ingress.defaultRoute.extraMiddlewares | toYaml) . | nindent 8 }}
        {{- end }}
      services:
      - kind: Service
        name: {{ include "service.name" $ }}
        namespace: {{ $.Release.Namespace }}
        passHostHeader: true
        {{- range $port := $.Values.service.ports }}
          {{- if eq $port.name "http" }}
        port: {{ $port.port }}
          {{- end }}
        {{- end }}
    {{- range .Values.ingress.extraRoutes }}
    - kind: Rule
      match: {{  printf "%s" (tpl .match $) }}
      {{- if .customMiddlewares }}
      middlewares:
        {{- range .customMiddlewares }}
      - name: {{ .name }}
        namespace: {{ .namespace }}
        {{- end }}
      {{- end }}
      services:
      - kind: Service
        name: {{ include "service.name" $ }}
        namespace: {{ $.Release.Namespace }}
        passHostHeader: true
        {{- range $port := $.Values.service.ports }}
          {{- if eq $port.name "http" }}
        port: {{ $port.port }}
          {{- end }}
        {{- end }}
    {{- end }}
  {{- if $needsCertificate }}
  tls:
    secretName: {{ include "service.name" . }}-cert
  {{- else }}
  tls: {}
  {{- end }}
{{- if (and .Values.ingress.issuer $needsCertificate) }}
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "service.name" . }}-cert
  issuerRef:
    name: {{ .Values.ingress.issuer.name }}
    kind: ClusterIssuer
  additionalOutputFormats:
  - type: CombinedPEM
  dnsNames:
  {{- if not $wildcardMode }}
  - {{  printf "%s.%s" (include "service.name" .) (include "cluster.fqdn" .) }}
  {{- end }}
  {{- range $extraCertHosts }}
  - {{ . }}
  {{- end }}
{{- end }}
{{- end }}

{{- range .Values.customMiddleware.definitions }}
---
{{ include "service.render" (dict "value" . "context" $) }}
{{- end }}
