{{- if .Values.ingress.create }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    external-dns.alpha.kubernetes.io/target: k3s.internal.{{ .Values.topLevelDomain }}
    kubernetes.io/ingress.class: traefik
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  entryPoints:
    - websecure
  routes:
  - kind: Rule
    match: Host(`{{ include "service.name" . }}.k3s.internal.{{ .Values.topLevelDomain }}`){{ if .Values.ingress.publiclyAvailable }} || Host(`{{ include "service.name" . }}.{{ .Values.topLevelDomain }}`) {{ end }}
    services:
    - kind: Service
      name: {{ include "service.name" . }}
      namespace: {{ .Release.Namespace }}
      passHostHeader: true
      {{- range $port := .Values.service.ports }}
        {{- if eq $port.name "http" }}
      port: {{ $port.port }}
        {{- end }}
      {{- end }}
  tls:
    secretName: {{ include "service.name" . }}-cert
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ include "service.name" . }}-cert
  issuerRef:
    name: {{ .Values.ingress.issuer.name }}
    kind: ClusterIssuer
  dnsNames:
    - {{ include "service.name" . }}.k3s.internal.{{ .Values.topLevelDomain }}
    {{- if .Values.ingress.publiclyAvailable -}}
      {{- printf "- %s.%s" (include "service.name" .) .Values.topLevelDomain | nindent 4 -}}
    {{ end }}
{{- end }}
