{{- range $value := .Values.externalSecrets }}
apiVersion: secrets.hashicorp.com/v1beta1
kind: VaultStaticSecret
metadata:
  name: {{ $value.name }}
  namespace: vault-secrets-operator-system
spec:
  type: kv-v2
  mount: homelab
  path: {{ $value.path }}
  destination:
    name: {{ $value.name }}
    create: true
  refreshAfter: {{ $value.refreshAfter | default "300s" }}
  vaultAuthRef: vault-secrets-operator-system/default-auth
{{- end }}
