{{- range $value := .Values.externalSecrets }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ tpl $value.name $ }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "service.labels" $ | nindent 4 }}
spec:
  refreshInterval: {{ $value.refreshInterval | default "300s" }}
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: {{ tpl $value.name $ }}
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: {{ tpl $value.path $ }}
{{- end }}
