apiVersion: v1
kind: Service
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ tpl .Values.deployment.name . }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  {{- if or (.Values.service.ports) (.Values.monitoring.exportarr.create) }}
  ports:
    {{- with .Values.service.ports }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.monitoring.exportarr.create }}
    - name: monitoring
      port: 9707
    {{- end }}
  {{- end }}
