{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "service.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/component: authorization
    {{- include "service.labels" . | nindent 4 }}
{{- end }}
---
{{- if (and .Values.serviceAccount.create .Values.serviceAccount.secret.create) }}
apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: {{ include "service.name" . }}-token
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "service.labels" . | nindent 4 }}
  annotations:
    kubernetes.io/service-account.name: {{ include "service.name" . }}
{{- end }}
---
{{- with .Values.clusterRole.rules }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "service.name" $ }}
  labels:
    {{- include "service.labels" $ | nindent 4 }}
rules:
  {{- toYaml . | nindent 2 }}
{{- end }}
---
{{- with .Values.clusterRoleBinding }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "service.name" $ }}
  labels:
    {{- include "service.labels" $ | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ tpl .role $ }}
subjects:
  - kind: ServiceAccount
    name: {{ tpl .serviceAccount.name $ }}
    namespace: {{ tpl .serviceAccount.namespace $ }}
{{- end }}
