name: Validate Charts

on:
  pull_request:
    branches:
      - 'main'


jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Helm
        uses: azure/setup-helm@v4.0.0

      - name: Helm Lint
        run: |
          helm lint charts/homelab-service

      - name: Helm Render
        run: |
          helm template charts/homelab-service > rendered.yml

      - name: Login to Github Packages
        run: echo "${{ github.token }}" | docker login https://ghcr.io -u ${GITHUB_ACTOR} --password-stdin

      - uses: docker://ghcr.io/yannh/kubeconform:latest
        with:
          args: "-ignore-missing-schemas rendered.yml"

      - name: Check version increment
        run: |
          chart_path=${1:?"No chart path provided to [Version Check]"}
          target_branch=${2:?"No target branch provided to [Version Check]"}
          "origin/${{ github.base_ref }}"
          new=$(git diff "origin/${{ github.base_ref }}" -- ${{ github.workspace }}/charts/homelab-service/Chart.yaml | sed -nr 's/^\+version: (.*)$/\1/p')
          old=$(git diff "origin/${{ github.base_ref }}" -- ${{ github.workspace }}/charts/homelab-service/Chart.yaml | sed -nr 's/^\-version: (.*)$/\1/p')

          if [[ -z "$new" ]]; then
              echo -e "\t❌ Chart version: Not changed"
              return -1
          fi

          if [[ -n "$new" ]]; then
              echo -e "\t Old Chart Version: $old"
              echo -e "\t New Chart Version: $new"

              if [[ $(echo "$new\n$old" | sort -V -r | head -n1) != "$old" ]]; then
                  echo -e "\t✅ Chart version: Bumped"
              else
                  echo -e "\t❌ Chart version: Not bumped or downgraded"
                  curr_result=1
              fi
          fi
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}


